In [ ]:
import numpy as np

# File path
file_path = '/content/drive/MyDrive/Colab Notebooks/testmarks2.csv'

# Read the file using np.genfromtxt() with the correct delimiter, dtype, and skip_header parameters
dataset = np.genfromtxt(file_path, delimiter=',', dtype=float, skip_header=1)

# Matrix operations
dataset_transpose = dataset.T
matrix_product = np.dot(dataset_transpose, dataset)
matrix_inverse = np.linalg.inv(matrix_product)

# Horizontal and vertical stacking
hor_stack = np.hstack(dataset)
ver_stack = np.vstack(dataset)

# Custom sequence generation
custom_sequence = np.arange(0, len(dataset), 2)

# Arithmetic and Statistical Operations
addition = dataset[:, 1] + dataset[:, 2]
subtraction = dataset[:, 3] - dataset[:, 4]
multiplication = dataset[:, 1] * dataset[:, 3]
division = dataset[:, 2] / dataset[:, 4]
mean_col1 = np.mean(dataset[:, 1])
median_col2 = np.median(dataset[:, 2])
std_dev_col3 = np.std(dataset[:, 3])
max_col4 = np.max(dataset[:, 4])
min_col5 = np.min(dataset[:, 4])

# Mathematical Operations
exponential = np.exp(dataset[:, 1])
sqrt_col2 = np.sqrt(dataset[:, 2])
log_col3 = np.log(dataset[:, 3])

# Bitwise Operators
bitwise_and = np.bitwise_and(dataset[:, 2].astype(int), dataset[:, 4].astype(int))
bitwise_or = np.bitwise_or(dataset[:, 2].astype(int), dataset[:, 4].astype(int))

# Copying and Viewing Arrays
copy_col1 = np.copy(dataset[:, 1])
view_col3 = dataset[:, 3].view()

# Data Stacking
col_stack = np.column_stack((dataset[:, 1], dataset[:, 3]))
row_stack = np.row_stack((dataset[:, 2], dataset[:, 4]))

# Searching
index = np.where(dataset[:, 1] == 28.63)

# Sorting
sorted_col2 = np.sort(dataset[:, 2])

# Counting
count_col4 = np.count_nonzero(dataset[:, 4])

# Broadcasting
broadcasted_col1 = dataset[:, 1] * 2

# Print the results
print("Dataset Transpose:\n", dataset_transpose)
print("Matrix Product:\n", matrix_product)
print("Matrix Inverse:\n", matrix_inverse)
print("Horizontal Stack:\n", hor_stack)
print("Vertical Stack:\n", ver_stack)
print("Custom Sequence:\n", custom_sequence)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)
print("Mean of Column 1:", mean_col1)
print("Median of Column 2:", median_col2)
print("Standard Deviation of Column 3:", std_dev_col3)
print("Maximum of Column 4:", max_col4)
print("Minimum of Column 5:", min_col5)
print("Exponential of Column 1:\n", exponential)
print("Square Root of Column 2:\n", sqrt_col2)
print("Logarithm of Column 3:\n", log_col3)
print("Bitwise AND of Column 2 and Column 4:\n", bitwise_and)
print("Bitwise OR of Column 2 and Column 4:\n", bitwise_or)
print("Copy of Column 1:\n", copy_col1)
print("View of Column 3:\n", view_col3)
print("Column Stack:\n", col_stack)
print("Row Stack:\n", row_stack)
print("Index of 28.63 in Column 1:", index)
print("Sorted Column 2:\n", sorted_col2)
print("Count of Nonzero values in Column 4:", count_col4)
print("Broadcasted Column 1:\n", broadcasted_col1)


Dataset Transpose:
 [[801.   802.   803.   804.   805.   806.   807.   808.   809.   810.  ]
 [ 28.48  28.1   26.16  26.16  26.1   25.45  26.16  27.44  28.63  30.35]
 [ 34.18  33.72  31.39  31.39  31.32  30.54  31.39  32.93  34.35  36.42]
 [ 30.56  30.68  28.2   28.78  28.22  27.73  28.01  28.83  31.03  31.38]
 [ 22.23  22.82  22.53  20.93  20.82  21.05  20.51  22.08  22.68  23.1 ]]
Matrix Product:
 [[6.48838500e+06 2.19938810e+05 2.63921710e+05 2.36354900e+05
  1.76204910e+05]
 [2.19938810e+05 7.47642270e+03 8.97154730e+03 8.02993280e+03
  5.98322070e+03]
 [2.63921710e+05 8.97154730e+03 1.07656649e+04 9.63574310e+03
  7.17973390e+03]
 [2.36354900e+05 8.02993280e+03 9.63574310e+03 8.62732000e+03
  6.42812460e+03]
 [1.76204910e+05 5.98322070e+03 7.17973390e+03 6.42812460e+03
  4.79334490e+03]]
Matrix Inverse:
 [[ 1.07127833e-04  1.07799297e-01 -8.77392904e-02 -3.10404289e-03
  -2.91351984e-03]
 [ 1.07799297e-01  2.51526524e+04 -2.09296713e+04 -3.58948211e+01
  -2.64083690e+00]
 [-8.7739